/* XPM */
static char *pm_99[] = {
/* width height ncolors chars_per_pixel */
"25 35 1 1",
/* colors */
"  c #FF0000",
/* pixels */
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         "
};
/* XPM */
static char *pm_0[] = {
/* width height ncolors chars_per_pixel */
"25 35 1 1",
/* colors */
"  c #948D13",
/* pixels */
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         "
};
/* XPM */
static char *pm_11[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #B00000",
". c #EAEAEA",
"X c #063A30",
/* pixels */
".........................",
"...X........... . . . ...",
"...X..... .X.... . . . ..",
"..XX.   .  X... . . . . .",
".XX.....  ..X. . . .   . ",
".XX.....    X..     . . .",
".XX...  . ..X. . . .   . ",
"X.X.. . . ...X.       . .",
"X.X.. ... X..X X X   .   ",
"X.X.. .. ..X.X.XX .     .",
"X.X.. .X...X.X X  X .  . ",
"X.X.. ..X..X.X.X X X  . .",
"X..X. ..X..XXXXXXXX  . . ",
"X.XX. ..X.X . . .XX  .. .",
"X .X. ..XXX X X XXX.. ...",
"X. XXXX.X. . . . XX......",
"X .XX.X.XX X X X XXXX....",
"X. XX.X.X . . . .XXXXX...",
"X .XX...XXXXXXXXX.XX..XX.",
"X.XXX...XXX. . XX...X...X",
"XXX.XX..XX. . .X.XX..X...",
"XX...XXXXX . . .X.XXX....",
"X.........X . .X.X.X.XX..",
".......... XXXXXXXXXXXXXX",
".........  ..  .  .......",
"........  . .. .. .......",
"....... ... .. ... ......",
"......  ....... .........",
"...... . ...... .........",
"...... ...XXXXX X........",
"...XXXX XX.... ..X.X.X...",
".X.X.......... ..X..X....",
"..XX....... . ...XXX.X...",
"...XX.......  .....X...X.",
"XXXX.....   .. .....XXXXX"
};
/* XPM */
static char *pm_12[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
"          .....          ",
"         ... ...         ",
"          .. ..          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .....          ",
"         ... ...         ",
"          .....          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .. ..          ",
"         ... ...         ",
"          .....          ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"          .....          ",
"         ... ...         ",
"          .. ..          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .....          ",
"         ... ...         ",
"          .....          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .. ..          ",
"         ... ...         ",
"          .....          "
};
/* XPM */
static char *pm_13[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
"          .....          ",
"         ... ...         ",
"          .. ..          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .....          ",
"         ... ...         ",
"          .....          ",
"           . .           ",
"           . .           ",
"           . .           ",
"          .. ..          ",
"         ... ...         ",
"          .....          ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
" .....             ..... ",
"... ...           ... ...",
" .. ..             .. .. ",
"  . .               . .  ",
"  . .               . .  ",
"  . .               . .  ",
" .....             ..... ",
"... ...           ... ...",
" .....             ..... ",
"  . .               . .  ",
"  . .               . .  ",
"  . .               . .  ",
" .. ..             .. .. ",
"... ...           ... ...",
" .....             ..... "
};
/* XPM */
static char *pm_14[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
"   .....         .....   ",
"  ... ...       ... ...  ",
"   .. ..         .. ..   ",
"    . .           . .    ",
"    . .           . .    ",
"    . .           . .    ",
"   .....         .....   ",
"  ... ...       ... ...  ",
"   .....         .....   ",
"    . .           . .    ",
"    . .           . .    ",
"    . .           . .    ",
"   .. ..         .. ..   ",
"  ... ...       ... ...  ",
"   .....         .....   ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"   .....         .....   ",
"  ... ...       ... ...  ",
"   .. ..         .. ..   ",
"    . .           . .    ",
"    . .           . .    ",
"    . .           . .    ",
"   .....         .....   ",
"  ... ...       ... ...  ",
"   .....         .....   ",
"    . .           . .    ",
"    . .           . .    ",
"    . .           . .    ",
"   .. ..         .. ..   ",
"  ... ...       ... ...  ",
"   .....         .....   "
};
/* XPM */
static char *pm_15[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #B00000",
". c #EAEAEA",
"X c #063A30",
/* pixels */
".XXXXX.............XXXXX.",
"XXX.XXX...........XXX.XXX",
".XX.XX.............XX.XX.",
"..X.X...............X.X..",
"..X.X...............X.X..",
"..X.X...............X.X..",
".XXXXX.............XXXXX.",
"XXX.XXX...........XXX.XXX",
".XXXXX.............XXXXX.",
"..X.X...............X.X..",
"..X.X.....     .....X.X..",
"..X.X....   .   ....X.X..",
".XX.XX....  .  ....XX.XX.",
"XXX.XXX.... . ....XXX.XXX",
".XXXXX..... . .....XXXXX.",
"........... . ...........",
"..........     ..........",
".........   .   .........",
"..........     ..........",
"........... . ...........",
".XXXXX..... . .....XXXXX.",
"XXX.XXX.... . ....XXX.XXX",
".XX.XX....  .  ....XX.XX.",
"..X.X....   .   ....X.X..",
"..X.X.....     .....X.X..",
"..X.X...............X.X..",
".XXXXX.............XXXXX.",
"XXX.XXX...........XXX.XXX",
".XXXXX.............XXXXX.",
"..X.X...............X.X..",
"..X.X...............X.X..",
"..X.X...............X.X..",
".XX.XX.............XX.XX.",
"XXX.XXX...........XXX.XXX",
".XXXXX.............XXXXX."
};
/* XPM */
static char *pm_16[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
" .....    .....    ..... ",
"... ...  ... ...  ... ...",
" .. ..    .. ..    .. .. ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
" .....    .....    ..... ",
"... ..   ... ...  ... ...",
" .....    .....    ..... ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
" .. ..    .. ..    .. .. ",
"... ...  ... ...  ... ...",
" .....    .....    ..... ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
" .....    .....    ..... ",
"... ...  ... ...  ... ...",
" .. ..    .. ..    .. .. ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
" .....    .....    ..... ",
"... ..   ... ...  ... ...",
" .....    .....    ..... ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
"  . .      . .      . .  ",
" .. ..    .. ..    .. .. ",
"... ...  ... ...  ... ...",
" .....    .....    ..... "
};
/* XPM */
static char *pm_17[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #B00000",
". c #EAEAEA",
"X c #063A30",
/* pixels */
"..........     ..........",
".........   .   .........",
"..........  .  ..........",
"........... . ...........",
"..........     ..........",
".........   .   .........",
"..........     ..........",
"........... . ...........",
"..........  .  ..........",
".........   .   .........",
"..........     ..........",
".........................",
".XXXXX....XXXXX....XXXXX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XX.XX....XX.XX....XX.XX.",
"..X.X......X.X......X.X..",
".XXXXX....XXXXX....XXXXX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XXXXX....XXXXX....XXXXX.",
"..X.X......X.X......X.X..",
".XX.XX....XX.XX....XX.XX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XXXXX....XXXXX....XXXXX.",
".........................",
".XXXXX....XXXXX....XXXXX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XX.XX....XX.XX....XX.XX.",
"..X.X......X.X......X.X..",
".XXXXX....XXXXX....XXXXX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XXXXX....XXXXX....XXXXX.",
"..X.X......X.X......X.X..",
".XX.XX....XX.XX....XX.XX.",
"XXX.XXX..XXX.XXX..XXX.XXX",
".XXXXX....XXXXX....XXXXX."
};
/* XPM */
static char *pm_18[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
" .....             ..... ",
"... ...           ... ...",
" .. ..             .. .. ",
"  . .               . .  ",
"  . .     .....     . .  ",
"  . .     .. ..     . .  ",
" .....    . ...    ..... ",
"... ... .. ... .. ... ...",
" ..... ....   .... ..... ",
"  . . .. ..   .. .. . .  ",
"  . . ....     .... . .  ",
"  . .. ..       .. .. .  ",
" .. . .           ... .. ",
"... ...           ... ...",
" .....             ..... ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
" .....             ..... ",
"... ...           ... ...",
" .. . .           . . .. ",
"  . .. ..       .. .. .  ",
"  . . ....     .... . .  ",
"  . . .. ..   .. .. . .  ",
" ..... ....   .... ..... ",
"... ... .. ... .. ... ...",
" .....    ... .    ..... ",
"  . .     .. ..     . .  ",
"  . .     .....     . .  ",
"  . .               . .  ",
" .. ..             .. .. ",
"... ...           ... ...",
" .....             ..... "
};
/* XPM */
static char *pm_19[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #B00000",
". c #EAEAEA",
"X c #063A30",
/* pixels */
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XX.XX....  .  ....XX.XX.",
"..X.X...... . ......X.X..",
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX.",
"..X.X...... . ......X.X..",
".XX.XX....  .  ....XX.XX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX.",
".........................",
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XX.XX....  .  ....XX.XX.",
"..X.X...... . ......X.X..",
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX.",
"..X.X...... . ......X.X..",
".XX.XX....  .  ....XX.XX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX.",
".........................",
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XX.XX....  .  ....XX.XX.",
"..X.X...... . ......X.X..",
".XXXXX....     ....XXXXX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX.",
"..X.X...... . ......X.X..",
".XX.XX....  .  ....XX.XX.",
"XXX.XXX..   .   ..XXX.XXX",
".XXXXX....     ....XXXXX."
};
/* XPM */
static char *pm_21[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXX  XXXXX",
"XXXXXXXXXXX           XXX",
"XX          XXXXXXXX   XX",
"XXX    XXXXXXXXXXXXX   XX",
"XXXX XXXXXXXXXXXXXXXX  XX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_22[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX   XXXXXXXXX",
"XXXXXXXXXX       XXXXXXXX",
"XXXXX      XXXXXXXXXXXXXX",
"XXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXX  XXXXXX",
"XXXXXXXXXXX          XXXX",
"XXX         XXXXXXX   XXX",
"XXXX    XXXXXXXXXXX   XXX",
"XXXXX XXXXXXXXXXXXXX  XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_23[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXX",
"XXXXXXXXXXX       XXXXXXX",
"XXXXXXXX    XXXX  XXXXXXX",
"XXXXXX   XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX   XXXXXXXXX",
"XXXXXXXXXX       XXXXXXXX",
"XXXXXXXX   XXXX XXXXXXXXX",
"XXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX   XXXXXXX",
"XXXXXXXXX           XXXXX",
"XXXX      XXXXXXXX   XXXX",
"XXXXX  XXXXXXXXXXXX  XXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_24[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX         XXXXX",
"XXXX XX     XX  XX   XXXX",
"XXX       XXXX   XX   XXX",
"XXX   XX   XXX   XX   XXX",
"XXX   XXX   XX  XX    XXX",
"XXXX  XXXX  X  XXX   XXXX",
"XXXXX  XX           XXXXX",
"XXXXXX    XXXXXXX  XXXXXX",
"XXXXXXX XXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_25[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXX",
"XXXXXXXXXXXXXX    XXXXXXX",
"XXXXXX  XXXX       XXXXXX",
"XXXXXXX  X     XXXXXXXXXX",
"XXXXXX   XXXX  XXXXXXXXXX",
"XXXXXX   XXX  X  XXXXXXXX",
"XXXXXX  XXXX      XXXXXXX",
"XXXXX   X          XXXXXX",
"XXXXX   XX   XX  XXXXXXXX",
"XXXX  X XXX XX  X   XXXXX",
"XXXX XX XX            XXX",
"XXX XX      XXXXXXX    XX",
"XX XXX  XXXXXXXXXXXX   XX",
"XXXXXXX XXXXXXXXXXXXX XXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_26[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX  XXXXXXXXXXXX",
"XXXXXXXXXXXX  XXXXXXXXXXX",
"XXXXXXXXXXXX   XX XXXXXXX",
"XXXXXXXXXXXX  XX   XXXXXX",
"XXXXXXXXXXX         XXXXX",
"XXXX         XXXXX   XXXX",
"XXXXX  XXXX XXXXXX   XXXX",
"XXXXXXXX  XXX   XXX XXXXX",
"XXXXXXXXX   XX   XXXXXXXX",
"XXXXXXXXX  XXXX    XXXXXX",
"XXXXXXXX  XXXXXX   XXXXXX",
"XXXXXXX  XXXXXXXX  XXXXXX",
"XXXXXX XXXXXXXXXXX XXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_27[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX XXXXXXXX     XXX",
"XXXXXXXX   XXXXX     XXXX",
"XXXXXXXXX  XXXX  XXXXXXXX",
"XXXXXXXXX  XXX XXXXXXXXXX",
"XXXXXXXXXX XX XXXXXXXXXXX",
"XXXXXXXXXX X XXXXXXXXXXXX",
"XXXXXXXXXX  XXXXXXXXXXXXX",
"XXXXXXXXX    XX  XXXXXXXX",
"XXXXXXXX  X       XXXXXXX",
"XXXXXX   XXX       XXXXXX",
"XXX    XXXXXX     XXXXXXX",
"XXXX  XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_28[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX XXXXXXXXXXXX",
"XXXXXXXXXX    XXXXXXXXXXX",
"XXXXXXXXXXXX XXXXXXXXXXXX",
"XXXXXXXXXXXXX XXXXXXXXXXX",
"XXXXXXX XXXXX  XXXXXXXXXX",
"XXXXXXXX  XXXX  XXXXXXXXX",
"XXXXXXX    XXXX   XXXXXXX",
"XXXXXXX  X XXXXX     XXXX",
"XXXXXX  XXXXXXXXX       X",
"XXXX  XXXXXXXXXXXX    XXX",
"X   XXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_29[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXX    XXX  XXXXXXXXX",
"XXXXXXXX    XXX   XXXXXXX",
"XXXXXXXXX  XXX     XXXXXX",
"XXXXXXXXX       X  XXXXXX",
"XXXXX          XXXXXXXXXX",
"XXXXXXXXX  XX XXXXX XXXXX",
"XXXXXXXX   XX XXXXX XXXXX",
"XXXXXXXX  XXX XXXXX  XXXX",
"XXXXXXX  XXXX  XXX   XXXX",
"XXXXXX  XXXXXX        XXX",
"XXXXX  XXXXXXXX      XXXX",
"XXX  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXX.XXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXX",
"XXXXXXXX.XX.XX..XXXXXXXXX",
"XXXXXXXX..XXX..XXXXXXXXXX",
"XXXXXXXXX.X......XXXXXXXX",
"XXXXXXX.....X.XXXXXXXXXXX",
"XXXXXXXXXXX.....XXXXXXXXX",
"XXXXXXX.X....XX..XXXXXXXX",
"XXXXXXX..XX......XXXXXXXX",
"XXXXXXXX.X...X...XXXXXXXX",
"XXXXXXXX..XX....XXXXXXXXX",
"XXXXXXXX.....XX....XXXXXX",
"XXXX..XXX.X.....XX...XXXX",
"XXXXX.........XX.XX...XXX",
"XX.....XXXXX.X....XX...XX",
"XXX.X..........X..XX...XX",
"XXXXX.XX..XXXXXX..XX...XX",
"XXXXXXXXXXXXXX....X...XXX",
"XXXXXXXXXXXXXXXX.....XXXX"
};
/* XPM */
static char *pm_31[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #002065",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX       XXXXXXXXX",
"XXXXXXX  X X X X  XXXXXXX",
"XXXXXX X  X X X  X XXXXXX",
"XXXXX   XX X X XX   XXXXX",
"XXXX  XX X     X XX  XXXX",
"XXX X XX         XX X XXX",
"XXX  X    .....    X  XXX",
"XX X XX  ..X.X..  XX X XX",
"XX  X   ..X.X.X..   X  XX",
"XX X X  .X.....X.  X X XX",
"XX  X   ..X.X.X..   X  XX",
"XX X X  .X.....X.  X X XX",
"XX  X   ..X.X.X..   X  XX",
"XX X XX  ..X.X..  XX X XX",
"XXX  X    .....    X  XXX",
"XXX X XX         XX X XXX",
"XXXX  XX X     X XX  XXXX",
"XXXXX   XX X X XX   XXXXX",
"XXXXXX X  X X X  X XXXXXX",
"XXXXXXX  X X X X  XXXXXXX",
"XXXXXXXXX       XXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_32[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #002065",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
"..........     ..........",
".........  ...  .........",
"........ ..   .. ........",
"....... .       . .......",
"......  . . . . .  ......",
"...... .   . .   . ......",
"...... .  . . .  . ......",
"...... .   . .   . ......",
"......  . . . . .  ......",
"....... .       . .......",
"........ ..   .. ........",
".........  ...  .........",
"..........     ..........",
".........................",
".........................",
".........................",
"..........     ..........",
".........  ...  .........",
"........ ..   .. ........",
"....... .       . .......",
"......  . . . . .  ......",
"...... .   . .   . ......",
"...... .  . . .  . ......",
"...... .   . .   . ......",
"......  . . . . .  ......",
"....... .       . .......",
"........ ..   .. ........",
".........  ...  .........",
"..........     ..........",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_33[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #002065",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX     XXXXXXXXXXXXXXXXX",
"XX  XXX  XXXXXXXXXXXXXXXX",
"X  X   X  XXXXXXXXXXXXXXX",
"  X X X X  XXXXXXXXXXXXXX",
" X X X X X XXXXXXXXXXXXXX",
" X  X X  X XXXXXXXXXXXXXX",
" X X X X X XXXXXXXXXXXXXX",
"  X X X X  XXXXXXXXXXXXXX",
"X  X   X  XXXXXXXXXXXXXXX",
"XX  XXX  XXXXXXXXXXXXXXXX",
"XXX     XXXXXXXXXXXXXXXXX",
"XXXXXXXXXX.....XXXXXXXXXX",
"XXXXXXXXX..XXX..XXXXXXXXX",
"XXXXXXXX..X...X..XXXXXXXX",
"XXXXXXX..X.X.X.X..XXXXXXX",
"XXXXXXX.X.X.X.X.X.XXXXXXX",
"XXXXXXX.X..X.X..X.XXXXXXX",
"XXXXXXX.X.X.X.X.X.XXXXXXX",
"XXXXXXX..X.X.X.X..XXXXXXX",
"XXXXXXXX..X...X..XXXXXXXX",
"XXXXXXXXX..XXX..XXXXXXXXX",
"XXXXXXXXXX.....XXXXXXXXXX",
"XXXXXXXXXXXXXXXXX     XXX",
"XXXXXXXXXXXXXXXX  XXX  XX",
"XXXXXXXXXXXXXXX  X   X  X",
"XXXXXXXXXXXXXX  X X X X  ",
"XXXXXXXXXXXXXX X X X X X ",
"XXXXXXXXXXXXXX X  X X  X ",
"XXXXXXXXXXXXXX X X X X X ",
"XXXXXXXXXXXXXX  X X X X  ",
"XXXXXXXXXXXXXXX  X   X  X",
"XXXXXXXXXXXXXXXX  XXX  XX",
"XXXXXXXXXXXXXXXXX     XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_34[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #002065",
". c #EAEAEA",
/* pixels */
"....     .......     ....",
"...  ...  .....  ...  ...",
"..  .   .  ...  .   .  ..",
".  . . . .  .  . . . .  .",
". . . . . . . . . . . . .",
". .  . .  . . .  . .  . .",
". . . . . . . . . . . . .",
".  . . . .  .  . . . .  .",
"..  .   .  ...  .   .  ..",
"...  ...  .....  ...  ...",
"....     .......     ....",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
"....     .......     ....",
"...  ...  .....  ...  ...",
"..  .   .  ...  .   .  ..",
".  . . . .  .  . . . .  .",
". . . . . . . . . . . . .",
". .  . .  . . .  . .  . .",
". . . . . . . . . . . . .",
".  . . . .  .  . . . .  .",
"..  .   .  ...  .   .  ..",
"...  ...  .....  ...  ...",
"....     .......     ...."
};
/* XPM */
static char *pm_35[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #002065",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXX     XXXXXXX     XXXX",
"XXX  XXX  XXXXX  XXX  XXX",
"XX  X   X  XXX  X   X  XX",
"X  X X X X  X  X X X X  X",
"X X X X X X X X X X X X X",
"X X  X X  X X X  X X  X X",
"X X X X X X X X X X X X X",
"X  X X X X  X  X X X X  X",
"XX  X   X  XXX  X   X  XX",
"XXX  XXX  XXXXX  XXX  XXX",
"XXXX     XXXXXXX     XXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX.....XXXXXXXXXX",
"XXXXXXXXX..XXX..XXXXXXXXX",
"XXXXXXXX..X...X..XXXXXXXX",
"XXXXXXX..X.X.X.X..XXXXXXX",
"XXXXXXX.X.X.X.X.X.XXXXXXX",
"XXXXXXX.X..X.X..X.XXXXXXX",
"XXXXXXX.X.X.X.X.X.XXXXXXX",
"XXXXXXX..X.X.X.X..XXXXXXX",
"XXXXXXXX..X...X..XXXXXXXX",
"XXXXXXXXX..XXX..XXXXXXXXX",
"XXXXXXXXXX.....XXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXX     XXXXXXX     XXXX",
"XXX  XXX  XXXXX  XXX  XXX",
"XX  X   X  XXX  X   X  XX",
"X  X X X X  X  X X X X  X",
"X X X X X X X X X X X X X",
"X X  X X  X X X  X X  X X",
"X X X X X X X X X X X X X",
"X  X X X X  X  X X X X  X",
"XX  X   X  XXX  X   X  XX",
"XXX  XXX  XXXXX  XXX  XXX",
"XXXX     XXXXXXX     XXXX"
};
/* XPM */
static char *pm_36[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #002065",
". c #B00000",
"X c #EAEAEA",
"o c #FFFFFF",
/* pixels */
"XXXo     oXXXXXo     oXXX",
"XXo  ooo  oXXXo  ooo  oXX",
"Xo  o   o  oXo  o   o  oX",
"X  o o o o  X  o o o o  X",
"X X o o o X X X o o o X X",
"X X  o o  X X X  o o  X X",
"X o o o o o X o o o o o X",
"X  o o o o  X  o o o o  X",
"XX  o   o  XXX  o   o  XX",
"XXX  ooo  XXXXX  ooo  XXX",
"XXXX     XXXXXXX     XXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXX.....XXXXXXX.....XXXX",
"XXX..ooo..XXXXX..ooo..XXX",
"XX..o...o..XXX..o...o..XX",
"X..o.o.o.o..X..o.o.o.o..X",
"X.o.o.o.o.o.X.o.o.o.o.o.X",
"X.X..o.o..X.X.X..o.o..X.X",
"X.X.o.o.o.X.X.X.o.o.o.X.X",
"X..o.o.o.o..X..o.o.o.o..X",
"Xo..o...o..oXo..o...o..oX",
"XXo..ooo..oXXXo..ooo..oXX",
"XXXo.....oXXXXXo.....oXXX",
"XXX..ooo..XXXXX..ooo..XXX",
"XX..o...o..XXX..o...o..XX",
"X..o.o.o.o..X..o.o.o.o..X",
"X.o.o.o.o.o.X.o.o.o.o.o.X",
"X.X..o.o..X.X.X..o.o..X.X",
"X.X.o.o.o.X.X.X.o.o.o.X.X",
"X..o.o.o.o..X..o.o.o.o..X",
"Xo..o...o..oXo..o...o..oX",
"XXo..ooo..oXXXo..ooo..oXX",
"XXXo.....oXXXXXo.....oXXX"
};
/* XPM */
static char *pm_37[] = {
"25 35 3 1",
".	c #EAEAEA",
"+	c #002065",
"@	c #B00000",
"...+++...................",
".++...++.................",
".+.+++.+.................",
"+.++.++.+..+++...........",
"+.+.+.+.+++...++.........",
"+.++.++.++.+++.+.........",
".+.+++.++.++.++.+..+++...",
".++...+++.+.+.+.+++...++.",
"...+++..+.++.++.++.+++.+.",
".........+.+++.++.++.++.+",
".........++...+++.+.+.+.+",
"...........+++..+.++.++.+",
".................+.+++.+.",
".................++...++.",
"...................+++...",
".........................",
".....@@@.........@@@.....",
"...@@...@@.....@@...@@...",
"...@.@@@.@.....@.@@@.@...",
"..@.@@.@@.@...@.@@.@@.@..",
"..@.@.@.@.@...@.@.@.@.@..",
"..@.@@.@@.@...@.@@.@@.@..",
"...@.@@@.@.....@.@@@.@...",
"...@@...@@.....@@...@@...",
".....@@@.........@@@.....",
".....@@@.........@@@.....",
"...@@...@@.....@@...@@...",
"...@.@@@.@.....@.@@@.@...",
"..@.@@.@@.@...@.@@.@@.@..",
"..@.@.@.@.@...@.@.@.@.@..",
"..@.@@.@@.@...@.@@.@@.@..",
"...@.@@@.@.....@.@@@.@...",
"...@@...@@.....@@...@@...",
".....@@@.........@@@.....",
"........................."};
/* XPM */
static char *pm_38[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #002065",
". c #EAEAEA",
/* pixels */
".........................",
"......   .......   ......",
"....  ...  ...  ...  ....",
".... .   . ... .   . ....",
"... .  .  . . .  .  . ...",
"... . . . . . . . . . ...",
"... .  .  . . .  .  . ...",
".... .   . ... .   . ....",
"....  ...  ...  ...  ....",
"......   .......   ......",
"....  ...  ...  ...  ....",
".... .   . ... .   . ....",
"... .  .  . . .  .  . ...",
"... . . . . . . . . . ...",
"... .  .  . . .  .  . ...",
".... .   . ... .   . ....",
"....  ...  ...  ...  ....",
"......   .......   ......",
"....  ...  ...  ...  ....",
".... .   . ... .   . ....",
"... .  .  . . .  .  . ...",
"... . . . . . . . . . ...",
"... .  .  . . .  .  . ...",
".... .   . ... .   . ....",
"....  ...  ...  ...  ....",
"......   .......   ......",
"....  ...  ...  ...  ....",
".... .   . ... .   . ....",
"... .  .  . . .  .  . ...",
"... . . . . . . . . . ...",
"... .  .  . . .  .  . ...",
".... .   . ... .   . ....",
"....  ...  ...  ...  ....",
"......   .......   ......",
"........................."
};
/* XPM */
static char *pm_39[] = {
/* width height ncolors chars_per_pixel */
"25 35 3 1",
/* colors */
"  c #002065",
". c #B00000",
"X c #EAEAEA",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX   XXXXX   XXXXX   XXX",
"X  XXX  X  XXX  X  XXX  X",
"X X   X X X   X X X   X X",
" X  X  X X  X  X X  X  X ",
" X X X X X X X X X X X X ",
" X  X  X X  X  X X  X  X ",
"X X   X X X   X X X   X X",
"X  XXX  X  XXX  X  XXX  X",
"XXX   XXXXX   XXXXX   XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX...XXXXX...XXXXX...XXX",
"X..XXX..X..XXX..X..XXX..X",
"X.X...X.X.X...X.X.X...X.X",
".X..X..X.X..X..X.X..X..X.",
".X.X.X.X.X.X.X.X.X.X.X.X.",
".X..X..X.X..X..X.X..X..X.",
"X.X...X.X.X...X.X.X...X.X",
"X..XXX..X..XXX..X..XXX..X",
"XXX...XXXXX...XXXXX...XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX   XXXXX   XXXXX   XXX",
"X  XXX  X  XXX  X  XXX  X",
"X X   X X X   X X X   X X",
" X  X  X X  X  X X  X  X ",
" X X X X X X X X X X X X ",
" X  X  X X  X  X X  X  X ",
"X X   X X X   X X X   X X",
"X  XXX  X  XXX  X  XXX  X",
"XXX   XXXXX   XXXXX   XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_41[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #000000",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
"...........   ...........",
"............   ..........",
"............   ..........",
"............  ...........",
"............  .  ........",
"............      .......",
".......           .......",
".........     ...........",
"............  .   .......",
"...........        ......",
"......  .           .....",
"......    ..  ....   ....",
"......   ..      .   ....",
"......               ....",
".......   ..  ...   .....",
"........           ......",
".........  .  ..  .......",
"..........      .........",
".........     .  ........",
"........   .  ..  .......",
".......   ..  ..   ......",
"......   ...  ...   .....",
".....     ..  ...     ...",
"...  ....     ....     ..",
"..........    ...........",
"...........   ...........",
"............  ...........",
"............ ............",
".........................",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_42[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #000000",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
".........  ..............",
"..........    ...........",
"...........     .........",
"............   ..........",
"............   ..........",
"............  ...........",
"............  . .........",
"............     ........",
"...........       .......",
"........   .    .........",
"............  .  ........",
"............ ..   .......",
"....... ....      .......",
".......   .           ...",
"........      .  ..    ..",
".......     ..   ...   ..",
".. ...     .    ....   ..",
"... . ...     ..  ..  ...",
"...  ...   .       .  ...",
"....  ....     .....  ...",
"....   .   .  ......  ...",
".....   .... ......   ...",
"......  .....         ...",
"....... ........      ...",
"...................  ....",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_43[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #000000",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".................  ......",
"................    .....",
"............          ...",
".......      .....     ..",
"..      .....   .      ..",
"...  .........    .......",
"..............   ........",
"......  .....   .........",
".......  ....   .........",
".......  ... .  .........",
"........  ..      .......",
".......         .   .....",
"......    . ..  ..   ....",
"...    .  . ..  ...   ...",
"...   ...   .. ....   ...",
"...   ...   .  ...    ...",
"....   ...           ....",
".....               .....",
"......     ....    ......",
".......  ......   .......",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_44[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #000000",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".............   .........",
".............     .......",
"..............    .......",
"......... ....    .......",
".......    ...   ........",
".......     ..  ..   ....",
"........    ..  ..    ...",
".........  ...  .      ..",
"...     .  ...       ....",
"...     .  ...    .......",
"....   ..  ...  .........",
".........  ...  .........",
".........  . .  .........",
"... .....   ..   ........",
"...  ...   ...         ..",
"...        ....        ..",
"..      . .......     ...",
"...   ... ...............",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_51[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #B00000",
". c #EAEAEA",
/* pixels */
".........................",
".........................",
".........................",
".........................",
"............ ............",
"..........    ...........",
"...........    ..........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ....  .....",
"..  .......           ...",
"...  ....     .....    ..",
"....  .  ...  .....    ..",
"....    ....  .....    ..",
".....   ....  ....     ..",
".....    ...  ...   . ...",
"......              .....",
"......   ...  ..   ......",
".......  ...  ... .......",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............  ...........",
"............ ............",
"............ ............",
".........................",
".........................",
"........................."
};
/* XPM */
static char *pm_52[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #002060",
/* pixels */
"                         ",
"                         ",
"  ...................... ",
"  .                    . ",
"  . .................. . ",
"  . . .            . . . ",
"  . ..              .. . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . .                . . ",
"  . ..              .. . ",
"  . . .            . . . ",
"  . .................. . ",
"  .                    . ",
"  ...................... ",
"                         ",
"                         "
};
/* XPM */
static char *pm_53[] = {
/* width height ncolors chars_per_pixel */
"25 35 2 1",
/* colors */
"  c #EAEAEA",
". c #063A30",
/* pixels */
"                         ",
"                         ",
"                         ",
"                         ",
"              ..         ",
"               ...       ",
"                ...      ",
"           .    ..       ",
"           ..   .        ",
"        .  ... . .       ",
"        ..... .  ..      ",
"        . .....  ...     ",
"    .. . ...  .. ..      ",
"     ..  ... . ...       ",
"     .. ... .. ..        ",
"    . . .. .......       ",
"       .. .. .. ...      ",
"       . .. ........     ",
"      . .. .. .. ....    ",
"     . ....  .... ....   ",
"    . .. ... ..........  ",
"   . ..  ...... .... ... ",
"  . ... .............    ",
" . ...  ... .... ....    ",
"    .. ...........  .    ",
"     .... . ..  ...      ",
"      ..   ..   ....     ",
"          .      ...     ",
"                 ...     ",
"                 ..      ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         "
};
/* XPM */
static char *pm_61[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"...XXXXXXXXXXXXX XXXXXXXX",
"XX.XXXXXooXXXXXX  XX    X",
"XX.XXXXoooooXXXX XXXXXXXX",
"XX.XXXooooXoXXXX XXX   XX",
"X...XXooooXoXXX  X X XXXX",
"XXXXXXXXooXXXXX          ",
"XXXXXooooXXXXXXX X X XXXX",
"XXXXXoXXooooXXXX XXX   XX",
"XXXXXXooooXXoXXX XXX X XX",
"XXXXXXXooXXXoXXXXXXXX XXX",
"XXXXoXXoXXXXXXXXXXXXXXXXX",
"XXXoXoooXXXXXXXXXXXXXXXXX",
"XXXooXooooooXXXXXXoXXXXXX",
"XXXXXooXXXXXXXXXXXXoXXXXX",
"XXXXXXXX....XXXXXXoXXXXXX",
"XXXXXXX..XX..XXXXooXXXXXX",
"XXXXX....XX.....oXooXXXXX",
"XXXX.............XoXoXXXX",
"XXX..XX....X.XX..XoXoXXXX",
"XXXX.XX..XXX....XXXoXXXXX",
"XXXX......XX....XXoXXXXXX",
"XXXXX......X...XXXoXXXXXX",
"XXXooX..XX...X.XXXoXXXXXX",
"XooooX..XX..XX.XXooXXXXXX",
"oooooX.........XXooXXXXXX",
"XooooXXXXXXXXXXXXooXXXXXX",
"XooooXXooooooooXXooXXXXXX",
"XXoooooooXXXXooooooXXXXXX",
"XooXooXXXXXXXXXoooooXXXXX",
"XXXXXoXXXXXXXXXXXooooXXXX",
"XXXXXXXXXXXXXXXXXXXoooooX",
"XXXXXXXXXXXXXXXXXXXXooooX",
"XXXXXXXXXXXXXXXXXXXXXXooX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_62[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXX XX",
"XX....XXXXoXXXXXXXXX   XX",
"XX.XX.XXXXXoXXXXXX   XX X",
"XXXX..XXXXXoXXXXXX XXXX X",
"XXX..XXXXXXXoXXXXX XXX XX",
"XX..XXXXXXXXoXXXX        ",
"XX....XXXXXXoXXXXXX  XXXX",
"XXXXXXXXXXXXoXXXXX  XXXXX",
"XXXXXXXXXXXXoXXoX X XXXXX",
"XXXXXXXXXXXXooXXX X  XXXX",
"XXXXXXXXXXXXoXXXXX XXXXXX",
"XXXXXXXXXXXooXXXXXXXXXXXX",
"XXXoXXXXXXXoXXXXXXooooooX",
"XXoXXXXXXoXoXXoooooXoXXoX",
"XooXXXXXXXoXXoXXXXXXXXXoo",
"XoXXXoooXXooooXXXXXXXXXoo",
"ooXXXXXoXXoooXXXXXXXXXooX",
"ooXXXXXoXooXXXXXXXXXXXoXX",
"XXoXXXXoXoXXXXXXXXXXXXXXX",
"XXXXooXoooXXXXXXXXXXoXXXX",
"XXXXXooooXXXXXXXXoXXXXXXX",
"XXXXXXXooXXXXXXXXoXoXXXXX",
"XXXXXXXoooXXXXXXXXoXooXXX",
"XXXXXXXoooXXXXXXXXooXXXXX",
"XXXXXXXoXoXXoXXXXXoXXXXXX",
"XXXXXXXoXoXooXXXXXoXXXXXX",
"XXXXXXXoXoXoXXXXXXoXXXXXX",
"XXXXXXXoooooXXXXXXoXXXXXX",
"XXXXXXXXoooooXXXXXoXXXXXX",
"XXXXXXXooooooXXXXooXXXXXX",
"XXXXXXXXXXoooXXXXoXXXXXXX",
"XXXXXXXXXXXoooXXooXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_63[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"X....XXXXXXXXXXXXXXXXX  X",
"X.XX..XXXXXXXXXXXXXXXXXXX",
"XXX...XXXXXXXXXXXXX      ",
"XXX...XXXXXoXXoXXXXXXXXXX",
"XXXXX.XXXXXooooXXXXX XXXX",
"XX.X..XXXXXXooXXXX X XX X",
"XXX..XXooooXoXXXXXXX XXXX",
"XXXXXXXooooXoXXXXX      X",
"XXXXXXXXoooooXXXXXXX XXXX",
"XXXXXXXXXoooXXXXX  X XXXX",
"XXXoooXXXXooXXXXXXXXXXXXX",
"XXXooooXXXoXXXXXXXXXXXXXX",
"XXXXXXoXX.....XXXXXXXXXXX",
"XXXXXXo....X.....XXXXXXXX",
"XXXXXX.....XX....XXXXXXXX",
"XXXXXX..X..XX..X..XooXXXX",
"XXXXX.........XX..oXXXXXX",
"oooXX............XoooXXXX",
"oooXX.XX.........XXXXXXXX",
"ooXXX....X....XX..XXXXXXX",
"XXXXX..........XX.XXXXXXX",
"XXXXX..XX.........XXXXXXX",
"XXXXX.XXX........XXXooXXX",
"XXXXX.....XX..XXXXXoooXXX",
"XXXXXX....XX.XXXXXooXXXXX",
"XoXXXXXX.....XXXXXoXXXXXX",
"ooooooooX...XXXXXoXXXXXXX",
"oooXXXXoooXXXXXXXoXXXXXXX",
"XXXXXXXooooooXXXXooooooXX",
"XXXXXoooXXXooooooooooooXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_64[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX.XXXXXXXXXXXXXXXXXXXXX",
"XX..XXXXXXXXXXXXXXXXXXXXX",
"X...XXXXXXXXoXXXX X  XXXX",
"X.X.XXXXXXXoXXX       XXX",
"X....XXXXXoXXXXXX  X XXXX",
"XXX.XXXXXXoXXXXXX  X XXXX",
"XXXXXXXXXXoXXXXXX XXX XXX",
"XXXXXXXXXXoXXXXX  XXX XXX",
"XXXXXXXXXXooXXXX XXXX XXX",
"XXXXXXXXXXooXXXX XXX  XXX",
"XXXXXXXXXXooXXXXXoXXXXXXX",
"XXXXooXXXXoooXXXXoXXXXXXX",
"XXXoooXoXXXooXXXooXXXXXXX",
"XXXoXXXXoXXXoXXXXXXXXXoXX",
"XXoooXXXXoXXooXXXXXXooooX",
"XXXXXXXXXXoXXoXXooooooXXX",
"XXXXXXXXXXoXoooooXoXXooXX",
"XXXXXXooooooXooXoXXoXXooX",
"XXXXoooXoooXXXoXooXXXoXoX",
"XXXooXoooooXXXooXXXXXoXoX",
"XXoooXoooXoooooXXoooXXooX",
"XoXXoXooXXooXXooooXooXXoX",
"XoXXXXoXXXoXXXooXXXXXoooX",
"XoXoXXooXXooooooXXXXXXooX",
"XoooXXooXXXooXooXXXXXXoXX",
"XXoooXooXXXoXXXoXXXoXXXXX",
"XXoXXXXoXXXoXXXooXooXXXXX",
"XXXXXoooXXXooooooooXXooXX",
"XXXXXXXooXXooXXXooXXoXXXX",
"XXXXXXXXoXXoXXXXooXoXXXoX",
"XXXXXXXXooXooooooooXXXoXX",
"XXXXXoXXXoooXXXXXXXXXoXXX",
"XXXXXXXXXXoXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_71[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXX.XXXXXXXXXXXXXXXXXX",
"XXX....XXXXXXXXXXXXXXXXXX",
"XXXX.X...XXXXXXXXXXXXXXXX",
"XXXX.X.XXXXXXXXXXXoXXXX X",
"XXXX.X.....XXXXXXXoXXX  X",
"XXX......XXXXXXXoooXoX  X",
"X....XXX.XXXXXXXXooooXX X",
"XXX.......XXXXXXXoooXXX X",
"XX...XX..X..XXXXXooXXXX  ",
"X..X.....XXXXXXXXoXXXXXXX",
"XXXX.XX..XXXXXXoooooXXXXX",
"XXXX....XXXXXXXooooooXXXX",
"XXXXXXXXXXXXXXXooXoooXXXX",
"XXXXXXXXXXXXXXXooooXXXXXX",
"XXXXXXXXXXXXXXoooXXXooooX",
"XXXooooXXXXXXXXXXXooXXXoX",
"XXooXXooXXX.....XXoooXooX",
"XXooooooXX..XXX..XoXoooXX",
"XXXXXoX....XXXX..XXXXXXXX",
"XXXXXX..XX..XX.....XXXXXX",
"XXXXXX.XXX......XX.XXXXXX",
"XXXXXX.XXXX.XX.XXX..XXXXX",
"XXXXXXX.XXX....XXX..XXXXX",
"XXXXXXX.XX......X..XXXXXX",
"XXXXXXX.....XX....XXoooXX",
"XXXXXXXXXXX.XXX..XXooXooX",
"XXXXXXXXXXX.XXX.XoXoXXooX",
"XXXXXXXXXXX....XXoXoXXoXX",
"XXoooooooooooXoXXoooooXXX",
"XooooXXoooooooooXXooooXXX",
"ooooXXXXooXoooooooXoooXXX",
"oXoXXXXooooXXooooooooooXX",
"oooXXXXoooXXXXXXXXoXooooX",
"ooXXXXXXoXXXXXXXXXXXXXooX",
"XXXXXXXXXXXXXXXXXXXXXXXoX"
};
/* XPM */
static char *pm_72[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXX.XXXXXXXXXXXXX  XX",
"X.......XXXoXXXXXXX  X XX",
"XXXX..XXXXXooXXXXXX XX XX",
"XXX.....XXXXoXXXooXXX XXX",
"XXX.XXX.XXXXooXXoXXX XXXX",
"XXX.....XXXXXoXXoXX    XX",
"XX....X.XXXXXoXoooXXXXXXX",
"X..XX...XXXXXoXoooXXXXXXX",
"XXXXX..XXXXXXooXXoXXXXXXX",
"XX.......XXXXooooXXXXXXXX",
"XXXXXXXXXXXXXoooXXXXXoooX",
"XXoooXXXooXXXooXXXXXoooXX",
"XXXXooXooXXXXooXXXXoooooX",
"XXXXXoooXXXXXXXXXXooXXXXX",
"XXXXXooXXXXX..XXXXoXXXXXX",
"XXXXXooXXX.....XXXoooXXXX",
"XXXXXXoXX...XX..XooXXXXXX",
"XXXXXXoXX.X..XX.XoXXXXXXX",
"XXXXXXoXX.XX.XX..XXXXXXXX",
"XXXXXXoX...X..XX.XXXXXXXX",
"XooXXXXX.X.....X.XXXXXXXX",
"XXooXXXX.XX....X.XXXXXXXX",
"XXXXoXXX.XX..X....XXXXXXX",
"XXXXooXo....XX....XooXXXX",
"XXXXXoooXX..XXX..XooXXXXX",
"XXXXXooXXXX.....XXoXXXXXX",
"XXooXXooXXoooXXXXXXXXXXXX",
"XXXoXXXooXXXooooooXXXXXXX",
"XXXXoXXXoXXXXXXXXXXXXXXXX",
"XXXXXoXXooXXXooXXXXXXXXXX",
"XXXXXXoXooooooooooXXXXXXX",
"XXXXXXooooXXXXXXooXXXXXXX",
"XXXXXXXXXXXXXXXXXoXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_73[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX.XXXX.XXXXXXXoXXXX   X",
"XXX..XXX.XXXXXXXooXXXXX X",
"XXX...XX....XXXXXooXXXX X",
"X...XX...XXXXXXoooooX   X",
"XXX..XXX.XXXXXXoXXoXXXXX ",
"XXX...X...XXXXXooXoXX  X ",
"X...XX.XX..XXXXXoooXXX  X",
"XXX...XXXX..XXXXoooXXXXXX",
"XXX..XXXXXX..XXXXooXXXXXX",
"XXX.XXXXXXXXXXXXXooXXXXXX",
"XXXXXXXXXXXXXXXXXooXXXXXX",
"XoooooXXXXXoooooooooXXXXX",
"oooXXoXXXXXXoXXooXXoXXXXX",
"XoooooXXXXXXooXooXXoXXXXX",
"XXXXXXXXX..XXoooooooXXXXX",
"XXXXXX...X..XXXoXXXoXXXXX",
"XXXXX..XXXX..XXXXooooXXXX",
"XXXXX.XXXXXX.XXXooXXoXXXX",
"XXXX.....XXX..XXoooooXXXX",
"XXX..X.....XX..XXXooXXXXX",
"XXX..X..XX.XXX.XXXXXXXXXX",
"XXX......XX.XX.XXXXXXXXXX",
"XXX.X.XX..X.XX.XXXXXXXXXX",
"XXX.X..X..X.XX.XXXXXoooXX",
"XXX............XXXXooXoXX",
"XXXX....X....XXXoXoXXooXX",
"XXXXX.......XXXooooXooXXX",
"ooooooooooXXXXXXoooooXXXX",
"oXXooXooooooooooooooXXXXX",
"XXooXXoXXooXXXXXoooooXXXX",
"ooXXXXoXooXXXXXXXXoooooXX",
"XXXXXXoooXXXXXXXXXXXooooo",
"XXXXXXXoXXXXXXXXXXXXXXXXo",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_74[] = {
/* width height ncolors chars_per_pixel */
"25 35 4 1",
/* colors */
"  c #000000",
". c #B00000",
"X c #EAEAEA",
"o c #063A30",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXX...XXXXXXXXXXXXX XX",
"XXX......XXXoXXXXXXXX  XX",
"XXXX..X.XXXXoXXXXXXXX  XX",
"XXXXX...XXXXooXXXXXX X XX",
"XXXX....XXXXooXXXXXX     ",
"XX..XXX..XXXooXXXXXX    X",
"X..XXXXX..XoXoXXXXXXXXX X",
"X.XXX...XX.oooXXXXXXXXXXX",
"XXXXXXXXXXXXooXXXXXooooXX",
"XXXX....XXXXoXXXXXooXXooX",
"XXXXXXXXXXXoooooXooXXXXoX",
"XXXXXXXXXXXoooXXXoooooooX",
"XXXXXXoooXooXXXXXooXXXXXX",
"XXXXXooXoooXXXXXooooXXXXX",
"XXXXXooooooXXXXXooXooXXXX",
"XXXXXoXXooXXXXXXoXXoXXXXX",
"XXXXXXXXoX......ooooXXXXX",
"XXXXXXXXXX.XXXX.XXXXXXXXX",
"XXXXXXX....XXX....XXXXXXX",
"XXXXXX..X....X.....XXXXXX",
"XXXXXX..XX.....XXX.XXXXXX",
"XXXXXXX.XX.XX..XXX.XXXXXX",
"XXXXXXX....X...XXX.XXXXXX",
"XXXXXXXXX...X..XX..XXXXXX",
"XXXXXooXX.XXX.....XXXXXXX",
"XXooooooX.XXX.XXXXXooXXXX",
"XXoXXXXoo.....XXooooooXXX",
"XXoooXXXooXXXXXXoXXXXooXX",
"XXXXooooooXoooXooXXXXXooX",
"XXXXXXXXooooXoooooooXXXoX",
"XXXXXXXXXooXXoooXXXoooooX",
"XXXXXXXXXooXXXoXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *pm_101[] = {
/* width height ncolors chars_per_pixel */
"35 35 3 1",
/* colors */
"  c #000000",
". c None",
"X c #FFFFFF",
/* pixels */
".............         .............",
"..........   XXXXXXXXX   ..........",
"........  XXXXXXXXXXXXXXX  ........",
"....... XXXXXXXX   XXXXXXXX .......",
"...... XXXXXXXXXX   XXXXXXXX ......",
"..... XXXXXXXXXXX   XXXXXXXXX .....",
".... XXXXXXXXXXXX  XXXXXXXXXXX ....",
"... XXXXXXXXXXXXX  X  XXXXXXXXX ...",
".. XXXXXXXXXXXXXX      XXXXXXXXX ..",
".. XXXXXXXXX           XXXXXXXXX ..",
". XXXXXXXXXXXX     XXXXXXXXXXXXXX .",
". XXXXXXXXXXXXXXX  X   XXXXXXXXXX .",
". XXXXXXXXXXXXXX        XXXXXXXXX .",
" XXXXXXXXXX  X           XXXXXXXXX ",
" XXXXXXXXXX    XX  XXXX   XXXXXXXX ",
" XXXXXXXXXX   XX      X   XXXXXXXX ",
" XXXXXXXXXX               XXXXXXXX ",
" XXXXXXXXXXX   XX  XXX   XXXXXXXXX ",
" XXXXXXXXXXXX           XXXXXXXXXX ",
" XXXXXXXXXXXXX  X  XX  XXXXXXXXXXX ",
" XXXXXXXXXXXXXX      XXXXXXXXXXXXX ",
" XXXXXXXXXXXXX     X  XXXXXXXXXXXX ",
". XXXXXXXXXXX   X  XX  XXXXXXXXXX .",
". XXXXXXXXXX   XX  XX   XXXXXXXXX .",
". XXXXXXXXX   XXX  XXX   XXXXXXXX .",
".. XXXXXXX     XX  XXX     XXXXX ..",
".. XXXXX  XXXX     XXXX     XXXX ..",
"... XXXXXXXXXXX    XXXXXXXXXXXX ...",
".... XXXXXXXXXXX   XXXXXXXXXXX ....",
"..... XXXXXXXXXXX  XXXXXXXXXX .....",
"...... XXXXXXXXXX XXXXXXXXXX ......",
"....... XXXXXXXXXXXXXXXXXXX .......",
"........  XXXXXXXXXXXXXXX  ........",
"..........   XXXXXXXXX   ..........",
".............         ............."
};
/* XPM */
static char *pm_102[] = {
/* width height ncolors chars_per_pixel */
"35 35 3 1",
/* colors */
"  c #000000",
". c None",
"X c #FFFFFF",
/* pixels */
".............         .............",
"..........   XXXXXXXXX   ..........",
"........  XXXXXXXXXXXXXXX  ........",
"....... XXXXXX  XXXXXXXXXXX .......",
"...... XXXXXXXX    XXXXXXXXX ......",
"..... XXXXXXXXXX     XXXXXXXX .....",
".... XXXXXXXXXXXX   XXXXXXXXXX ....",
"... XXXXXXXXXXXXX   XXXXXXXXXXX ...",
".. XXXXXXXXXXXXXX  XXXXXXXXXXXXX ..",
".. XXXXXXXXXXXXXX  X XXXXXXXXXXX ..",
". XXXXXXXXXXXXXXX     XXXXXXXXXXX .",
". XXXXXXXXXXXXXX       XXXXXXXXXX .",
". XXXXXXXXXXX   X    XXXXXXXXXXXX .",
" XXXXXXXXXXXXXXXX  X  XXXXXXXXXXXX ",
" XXXXXXXXXXXXXXXX XX   XXXXXXXXXXX ",
" XXXXXXXXXXX XXXX      XXXXXXXXXXX ",
" XXXXXXXXXXX   X           XXXXXXX ",
" XXXXXXXXXXXX      X  XX    XXXXXX ",
" XXXXXXXXXXX     XX   XXX   XXXXXX ",
" XXXXXX XXX     X    XXXX   XXXXXX ",
" XXXXXXX X XXX     XX  XX  XXXXXXX ",
" XXXXXXX  XXX   X       X  XXXXXXX ",
". XXXXXXX  XXXX     XXXXX  XXXXXX .",
". XXXXXXX   X   X  XXXXXX  XXXXXX .",
". XXXXXXXX   XXXX XXXXXX   XXXXXX .",
".. XXXXXXXX  XXXXX         XXXXX ..",
".. XXXXXXXXX XXXXXXXX      XXXXX ..",
"... XXXXXXXXXXXXXXXXXXXX  XXXXX ...",
".... XXXXXXXXXXXXXXXXXXXXXXXXX ....",
"..... XXXXXXXXXXXXXXXXXXXXXXX .....",
"...... XXXXXXXXXXXXXXXXXXXXX ......",
"....... XXXXXXXXXXXXXXXXXXX .......",
"........  XXXXXXXXXXXXXXX  ........",
"..........   XXXXXXXXX   ..........",
".............         ............."
};
/* XPM */
static char *pm_103[] = {
/* width height ncolors chars_per_pixel */
"35 35 3 1",
/* colors */
"  c #000000",
". c None",
"X c #FFFFFF",
/* pixels */
".............         .............",
"..........   XXXXXXXXX   ..........",
"........  XXXXXXXXXXXXXXX  ........",
"....... XXXXXXXXXXXXXXXXXXX .......",
"...... XXXXXXXXXXXXXXXXXXXXX ......",
"..... XXXXXXXXXXXXXXXXXXXXXXX .....",
".... XXXXXXXXXXXXXXXXXXXXXXXXX ....",
"... XXXXXXXXXXXXXXXXXX  XXXXXXX ...",
".. XXXXXXXXXXXXXXXXXX    XXXXXXX ..",
".. XXXXXXXXXXXXXX          XXXXX ..",
". XXXXXXXXXX      XXXXX     XXXXX .",
". XXXXX      XXXXX   X      XXXXX .",
". XXXXXX  XXXXXXXXX    XXXXXXXXXX .",
" XXXXXXXXXXXXXXXXXX   XXXXXXXXXXXX ",
" XXXXXXXXXX  XXXXX   XXXXXXXXXXXXX ",
" XXXXXXXXXXX  XXXX   XXXXXXXXXXXXX ",
" XXXXXXXXXXX  XXX X  XXXXXXXXXXXXX ",
" XXXXXXXXXXXX  XX      XXXXXXXXXXX ",
" XXXXXXXXXXX         X   XXXXXXXXX ",
" XXXXXXXXXX    X XX  XX   XXXXXXXX ",
" XXXXXXX    X  X XX  XXX   XXXXXXX ",
" XXXXXXX   XXX   XX XXXX   XXXXXXX ",
". XXXXXX   XXX   X  XXX    XXXXXX .",
". XXXXXXX   XXX           XXXXXXX .",
". XXXXXXXX               XXXXXXXX .",
".. XXXXXXXX     XXXX    XXXXXXXX ..",
".. XXXXXXXXX  XXXXXX   XXXXXXXXX ..",
"... XXXXXXXXXXXXXXXXXXXXXXXXXXX ...",
".... XXXXXXXXXXXXXXXXXXXXXXXXX ....",
"..... XXXXXXXXXXXXXXXXXXXXXXX .....",
"...... XXXXXXXXXXXXXXXXXXXXX ......",
"....... XXXXXXXXXXXXXXXXXXX .......",
"........  XXXXXXXXXXXXXXX  ........",
"..........   XXXXXXXXX   ..........",
".............         ............."
};
/* XPM */
static char *pm_104[] = {
/* width height ncolors chars_per_pixel */
"35 35 3 1",
/* colors */
"  c #000000",
". c None",
"X c #FFFFFF",
/* pixels */
".............         .............",
"..........   XXXXXXXXX   ..........",
"........  XXXXXXXXXXXXXXX  ........",
"....... XXXXXXXXXXXXXXXXXXX .......",
"...... XXXXXXXXXXXXXXXXXXXXX ......",
"..... XXXXXXXXXXXXXXXXXXXXXXX .....",
".... XXXXXXXXXXXXXXXXXXXXXXXXX ....",
"... XXXXXXXXXXXXXXXXXXXXXXXXXXX ...",
".. XXXXXXXXXXXXXXXXXXXXXXXXXXXXX ..",
".. XXXXXXXXXXXXXXX   XXXXXXXXXXX ..",
". XXXXXXXXXXXXXXXX     XXXXXXXXXX .",
". XXXXXXXXXXXXXXXXX    XXXXXXXXXX .",
". XXXXXXXXXXXX XXXX    XXXXXXXXXX .",
" XXXXXXXXXXX    XXX   XXXXXXXXXXXX ",
" XXXXXXXXXXX     XX  XX   XXXXXXXX ",
" XXXXXXXXXXXX    XX  XX    XXXXXXX ",
" XXXXXXXXXXXXX  XXX  X      XXXXXX ",
" XXXXXXX     X  XXX       XXXXXXXX ",
" XXXXXXX     X  XXX    XXXXXXXXXXX ",
" XXXXXXXX   XX  XXX  XXXXXXXXXXXXX ",
" XXXXXXXXXXXXX  XXX  XXXXXXXXXXXXX ",
" XXXXXXXXXXXXX  X X  XXXXXXXXXXXXX ",
". XXXXXX XXXXX   XX   XXXXXXXXXXX .",
". XXXXXX  XXX   XXX         XXXXX .",
". XXXXXX        XXXX        XXXXX .",
".. XXXX      X XXXXXXX     XXXXX ..",
".. XXXXX   XXX XXXXXXXXXXXXXXXXX ..",
"... XXXXXXXXXXXXXXXXXXXXXXXXXXX ...",
".... XXXXXXXXXXXXXXXXXXXXXXXXX ....",
"..... XXXXXXXXXXXXXXXXXXXXXXX .....",
"...... XXXXXXXXXXXXXXXXXXXXX ......",
"....... XXXXXXXXXXXXXXXXXXX .......",
"........  XXXXXXXXXXXXXXX  ........",
"..........   XXXXXXXXX   ..........",
".............         ............."
};
char **fallbackpixmaps[] = {
pm_0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, pm_11, pm_12, pm_13, pm_14, pm_15, pm_16, pm_17, pm_18, pm_19, 0, pm_21, pm_22, pm_23, pm_24, pm_25, pm_26, pm_27, pm_28, pm_29, 0, pm_31, pm_32, pm_33, pm_34, pm_35, pm_36, pm_37, pm_38, pm_39, 0, pm_41, pm_42, pm_43, pm_44, 0, 0, 0, 0, 0, 0, pm_51, pm_52, pm_53, 0, 0, 0, 0, 0, 0, 0, pm_61, pm_62, pm_63, pm_64, 0, 0, 0, 0, 0, 0, pm_71, pm_72, pm_73, pm_74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, pm_99, 0, pm_101, pm_102, pm_103, pm_104, 
};
